[rank: 0] Seed set to 23
/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/site-packages/taming/modules/losses/lpips.py:29: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.load_state_dict(torch.load(ckpt, map_location=torch.device("cpu")), strict=False)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/site-packages/academictorrents/Torrent.py", line 25, in __init__
    contents = open("/tmp/" + hash + '.torrent', 'rb').read()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/a306397ccf9c2ead27155983c254227c0fd938e2.torrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/main.py", line 699, in <module>
    data.prepare_data()
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/main.py", line 198, in prepare_data
    instantiate_from_config(data_cfg)
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/ldm/data/imagenet.py", line 380, in __init__
    super().__init__(**kwargs)
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/ldm/data/imagenet.py", line 294, in __init__
    self.base = self.get_base()
                ^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/ldm/data/imagenet.py", line 385, in get_base
    dset = ImageNetTrain(process_images=False, data_root=self.data_root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/ldm/data/imagenet.py", line 148, in __init__
    super().__init__(**kwargs)
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/ldm/data/imagenet.py", line 33, in __init__
    self._prepare()
  File "/isilon/datalake/cialab/scratch/cialab/Hao/work_record/Project4_ear/codes/vq_imageNet/latent-diffusion/ldm/data/imagenet.py", line 171, in _prepare
    atpath = at.get(self.AT_HASH, datastore=self.root)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/site-packages/academictorrents/academictorrents.py", line 19, in get
    torrent = Torrent(at_hash, datastore)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/site-packages/academictorrents/Torrent.py", line 29, in __init__
    contents = self.get_from_url()
               ^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/site-packages/academictorrents/Torrent.py", line 103, in get_from_url
    response = urlopen(url, timeout=5).read()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/isilon/datalake/cialab/scratch/cialab/Hao/miniconda3/envs/vqVAE/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
